### ISSUE TITLE
Sqlite support require

### ISSUE THREAD

**Issue by SudoUserReal** [MakinoharaShoko/CloudLog.JS#1]
**Hopefully sqlite support will be the next milestone.**

Since sqlite can use one file to store all the data and does not require user installation.
Cloudlog can use sqlite to store logs by default, so cloudlog users can use the database function with 0 configuration. Sqlite is better for this project than MongoDB.

**Comment by MakinoharaShoko** [comment]
I will consider adding sqlite support in the near future, thank you for your suggestion.
